// Barrel exports de las páginas del panel administrativo
export { LoginPage } from './LoginPage'
export { DashboardPage } from './DashboardPage'
export { PostListPage } from './posts/PostListPage'
export { PostEditorPage } from './posts/PostEditorPage'
export { MediaLibraryPage } from './media/MediaLibraryPage'
export { CategoriesPage } from './taxonomy/CategoriesPage'
export { TagsPage } from './taxonomy/TagsPage'
export { UsersPage } from './users/UsersPage'
export { RedirectsPage } from './redirects/RedirectsPage'
export { AdsPage } from './ads/AdsPage'
export { SettingsPage } from './settings/SettingsPage'
export { AnalyticsPage } from './analytics/AnalyticsPage'
