import type { WhiteLabelConfig, WhiteLabelPreset } from '../types/settings';

export const DEFAULT_WHITE_LABEL_CONFIG: WhiteLabelConfig = {
  id: 'current_tenant',
  tenantName: 'Contacto con la Noticia Media Group',
  version: '2.0.0',
  updatedAt: new Date().toISOString(),
  identity: {
    siteName: 'Contacto con la Noticia',
    shortName: 'Contacto',
    tagline: '"Información oportuna, veraz y con sentido social para el estado Guárico y los Llanos Centrales"',
    historicSubtitle: 'Diario Regional Independiente · Fundado en 2011',
    editionName: 'Edición Digital · San Juan de los Morros, Guárico',
    centralLocation: 'San Juan de los Morros, Estado Guárico',
    address: 'Av. Bolívar, Edificio Centro Cívico, San Juan de los Morros, Estado Guárico',
    contactEmail: 'redaccion@contactoconlanoticia.com',
    contactPhone: '+58 (246) 431-2850',
    copyrightText: 'Contacto con la Noticia Media Group. Todos los derechos reservados.',
    showLyberateBadge: true,
  },
  logos: {
    headerLogoUrl: '',
    headerLogoHeight: 48,
    headerLogoDarkUrl: '',
    footerLogoUrl: '',
    faviconUrl: '/icons/icon.svg',
    ogFallbackImageUrl: '/placeholder-news.jpg',
    editorialWatermarkUrl: '',
  },
  colors: {
    primary: '#881337', // Rose 900
    primaryHover: '#4c0519', // Rose 950
    accent: '#b91c1c', // Red 700
    topBarBg: '#ffffff',
    topBarText: '#57534e',
    navBg: '#f5f5f4',
    navText: '#1c1917',
    pageBg: '#fafaf9',
    mastheadBg: '#ffffff',
    mastheadText: '#0c0a09',
    cardBg: '#ffffff',
  },
  typography: {
    headingFont: 'Merriweather',
    bodyFont: 'Inter',
    headingWeight: '900',
    scale: 'normal',
  },
  pwa: {
    appName: 'Contacto con la Noticia',
    shortName: 'Contacto',
    description: 'Periódico Digital de Guárico y Venezuela — Información veraz, inmediata y contrastada',
    themeColor: '#0c0a09',
    backgroundColor: '#ffffff',
    startUrl: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    icon192Url: '/icons/icon-192.png',
    icon512Url: '/icons/icon-512.png',
    iconMaskableUrl: '/icons/icon-maskable.png',
    iconSvgUrl: '/icons/icon.svg',
    shortcuts: [
      {
        name: 'Última Hora',
        shortName: 'Última Hora',
        description: 'Noticias más recientes de la edición',
        url: '/?seccion=ultimas',
        icon: '/icons/icon-192.png',
      },
      {
        name: 'Regionales',
        shortName: 'Regionales',
        description: 'Noticias del estado Guárico',
        url: '/categoria/regionales',
        icon: '/icons/icon-192.png',
      },
      {
        name: 'Buzón Ciudadano',
        shortName: 'Buzón',
        description: 'Envía tu denuncia o noticia comunitaria',
        url: '/enviar-noticia',
        icon: '/icons/icon-192.png',
      },
    ],
  },
  social: {
    twitterSite: '@contactonoticia',
    twitterUrl: 'https://x.com/contactonoticia',
    facebookUrl: 'https://facebook.com/contactonoticia',
    instagramUrl: 'https://instagram.com/contactonoticia',
    whatsappChannelUrl: 'https://whatsapp.com/channel/contactonoticia',
    telegramChannelUrl: 'https://t.me/contactonoticia',
    youtubeUrl: 'https://youtube.com/@contactonoticia',
  },
  features: {
    showBreakingNewsTicker: true,
    showWeatherWidget: true,
    showCitizenSubmissionButton: true,
    showSocialShareButtons: true,
    mastheadLayout: 'classic_double_rule',
  },
};

export const AVAILABLE_HEADING_FONTS = [
  { id: 'Merriweather', name: 'Merriweather (Clásica Periodística)', category: 'Serif' },
  { id: 'Lora', name: 'Lora (Elegante & Editorial)', category: 'Serif' },
  { id: 'Playfair Display', name: 'Playfair Display (Alta Gama & Prensa)', category: 'Serif' },
  { id: 'Cinzel', name: 'Cinzel (Institucional Solemne)', category: 'Serif' },
  { id: 'PT Serif', name: 'PT Serif (Contemporánea & Nítida)', category: 'Serif' },
  { id: 'Georgia', name: 'Georgia (Sistema Estándar)', category: 'Serif' },
];

export const AVAILABLE_BODY_FONTS = [
  { id: 'Inter', name: 'Inter (Moderna Hiper-legible)', category: 'Sans-Serif' },
  { id: 'Plus Jakarta Sans', name: 'Plus Jakarta Sans (Editorial UI)', category: 'Sans-Serif' },
  { id: 'Roboto', name: 'Roboto (Google Editorial)', category: 'Sans-Serif' },
  { id: 'Montserrat', name: 'Montserrat (Geométrica Distintiva)', category: 'Sans-Serif' },
  { id: 'Open Sans', name: 'Open Sans (Cálida y Neutral)', category: 'Sans-Serif' },
];

export const WHITE_LABEL_PRESETS: WhiteLabelPreset[] = [
  {
    id: 'contacto_default',
    name: 'Contacto Tradicional (Borgoña & Prensa)',
    description: 'Estilo editorial emblemático de los Llanos Centrales en tonos vino tinto y serif clásica.',
    config: {
      colors: {
        primary: '#881337',
        primaryHover: '#4c0519',
        accent: '#b91c1c',
        topBarBg: '#ffffff',
        topBarText: '#57534e',
        navBg: '#f5f5f4',
        navText: '#1c1917',
        pageBg: '#fafaf9',
        mastheadBg: '#ffffff',
        mastheadText: '#0c0a09',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Merriweather',
        bodyFont: 'Inter',
        headingWeight: '900',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'classic_double_rule',
      },
    },
  },
  {
    id: 'classic_navy',
    name: 'The Daily Tribune (Azul Marina Institucional)',
    description: 'Paleta sobria y de alta reputación periodística con tonos navy profundo y detalles azules.',
    config: {
      colors: {
        primary: '#1e3a8a',
        primaryHover: '#172554',
        accent: '#0284c7',
        topBarBg: '#0f172a',
        topBarText: '#cbd5e1',
        navBg: '#f1f5f9',
        navText: '#0f172a',
        pageBg: '#f8fafc',
        mastheadBg: '#ffffff',
        mastheadText: '#0f172a',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Playfair Display',
        bodyFont: 'Plus Jakarta Sans',
        headingWeight: '800',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'modern_centered',
      },
    },
  },
  {
    id: 'modern_crimson',
    name: 'Vanguardia Digital (Carbón & Crimson)',
    description: 'Identidad contemporánea para medios de investigación y breaking news de alto impacto.',
    config: {
      colors: {
        primary: '#0f172a',
        primaryHover: '#020617',
        accent: '#e11d48',
        topBarBg: '#ffffff',
        topBarText: '#334155',
        navBg: '#0f172a',
        navText: '#ffffff',
        pageBg: '#ffffff',
        mastheadBg: '#ffffff',
        mastheadText: '#020617',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Lora',
        bodyFont: 'Inter',
        headingWeight: '700',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: false,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'clean_compact',
      },
    },
  },
  {
    id: 'forest_emerald',
    name: 'Eco Periodismo (Bosque Esmeralda)',
    description: 'Paleta inspirada en ecología, regiones agropecuarias, ambiente y desarrollo sustentable.',
    config: {
      colors: {
        primary: '#065f46',
        primaryHover: '#064e3b',
        accent: '#059669',
        topBarBg: '#064e3b',
        topBarText: '#d1fae5',
        navBg: '#ecfdf5',
        navText: '#064e3b',
        pageBg: '#f0fdf4',
        mastheadBg: '#ffffff',
        mastheadText: '#064e3b',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'PT Serif',
        bodyFont: 'Roboto',
        headingWeight: '700',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'classic_double_rule',
      },
    },
  },
  {
    id: 'warm_amber',
    name: 'El Imparcial (Cálido Clásico & Ámbar)',
    description: 'Tonalidades cálidas de papel periódico tradicional con acentos dorados y elegancia sobria.',
    config: {
      colors: {
        primary: '#451a03',
        primaryHover: '#290d02',
        accent: '#d97706',
        topBarBg: '#fef3c7',
        topBarText: '#78350f',
        navBg: '#f5efe6',
        navText: '#451a03',
        pageBg: '#faf8f5',
        mastheadBg: '#ffffff',
        mastheadText: '#290d02',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Cinzel',
        bodyFont: 'Montserrat',
        headingWeight: '700',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'classic_double_rule',
      },
    },
  },
];

