import type { WhiteLabelConfig, WhiteLabelPreset } from '../types/settings';

export const DEFAULT_WHITE_LABEL_CONFIG: WhiteLabelConfig = {
  id: 'current_tenant',
  tenantName: 'Contacto con la Noticia Media Group',
  version: '2.0.0',
  updatedAt: new Date().toISOString(),
  identity: {
    siteName: 'Contacto con la Noticia',
    shortName: 'Contacto',
    tagline: '"Información oportuna, veraz y con sentido social para el estado Guárico y los Llanos Centrales"',
    historicSubtitle: 'Diario Regional Independiente · Fundado en 2011',
    editionName: 'Edición Digital · San Juan de los Morros, Guárico',
    centralLocation: 'San Juan de los Morros, Estado Guárico',
    address: 'Av. Bolívar, Edificio Centro Cívico, San Juan de los Morros, Estado Guárico',
    contactEmail: 'redaccion@contactoconlanoticia.com',
    contactPhone: '+58 (246) 431-2850',
    copyrightText: 'Contacto con la Noticia Media Group. Todos los derechos reservados.',
    showLyberateBadge: true,
  },
  logos: {
    headerLogoUrl: '',
    headerLogoHeight: 48,
    headerLogoDarkUrl: '',
    footerLogoUrl: '',
    faviconUrl: '/icons/icon.svg',
    ogFallbackImageUrl: '/placeholder-news.jpg',
    editorialWatermarkUrl: '',
  },
  colors: {
    primary: '#881337', // Rose 900
    primaryHover: '#4c0519', // Rose 950
    accent: '#a33a35',
    topBarBg: '#f4f0ea',
    topBarText: '#57534e',
    navBg: '#eee9e2',
    navText: '#1c1917',
    pageBg: '#f4f1eb',
    mastheadBg: '#ffffff',
    mastheadText: '#0c0a09',
    cardBg: '#ffffff',
  },
  typography: {
    headingFont: 'Merriweather',
    bodyFont: 'Open Sans',
    headingWeight: '900',
    scale: 'normal',
  },
  pwa: {
    appName: 'Contacto con la Noticia',
    shortName: 'Contacto',
    description: 'Periódico Digital de Guárico y Venezuela — Información veraz, inmediata y contrastada',
    themeColor: '#881337',
    backgroundColor: '#f4f1eb',
    startUrl: '/',
    display: 'standalone',
    orientation: 'portrait-primary',
    icon192Url: '/icons/icon-192.png',
    icon512Url: '/icons/icon-512.png',
    iconMaskableUrl: '/icons/icon-maskable.png',
    iconSvgUrl: '/icons/icon.svg',
    shortcuts: [
      {
        name: 'Última Hora',
        shortName: 'Última Hora',
        description: 'Noticias más recientes de la edición',
        url: '/?seccion=ultimas',
        icon: '/icons/icon-192.png',
      },
      {
        name: 'Regionales',
        shortName: 'Regionales',
        description: 'Noticias del estado Guárico',
        url: '/categoria/regionales',
        icon: '/icons/icon-192.png',
      },
      {
        name: 'Buzón Ciudadano',
        shortName: 'Buzón',
        description: 'Envía tu denuncia o noticia comunitaria',
        url: '/enviar-noticia',
        icon: '/icons/icon-192.png',
      },
    ],
  },
  social: {
    twitterSite: '@contactonoticia',
    twitterUrl: 'https://x.com/contactonoticia',
    facebookUrl: 'https://facebook.com/contactonoticia',
    instagramUrl: 'https://instagram.com/contactonoticia',
    whatsappChannelUrl: 'https://whatsapp.com/channel/contactonoticia',
    telegramChannelUrl: 'https://t.me/contactonoticia',
    youtubeUrl: 'https://youtube.com/@contactonoticia',
  },
  features: {
    showBreakingNewsTicker: true,
    showWeatherWidget: true,
    showCitizenSubmissionButton: true,
    showSocialShareButtons: true,
    mastheadLayout: 'classic_double_rule',
    showEconomicIndicators: true,
    showAudioReader: true,
    showComments: true,
    showReadingTime: true,
    showBookmarks: true,
    showPrintEdition: true,
    weatherCity: 'San Juan de los Morros',
    weatherTemp: '32°C',
    economicRates: {
      bcvRate: 'Bs. 54.12',
      parallelRate: 'Bs. 62.40',
      euroRate: 'Bs. 58.75',
    },
  },
};

export const AVAILABLE_HEADING_FONTS = [
  { id: 'Merriweather', name: 'Merriweather (Clásica Periodística)', category: 'Serif' },
  { id: 'Lora', name: 'Lora (Elegante & Editorial)', category: 'Serif' },
  { id: 'Playfair Display', name: 'Playfair Display (Alta Gama & Prensa)', category: 'Serif' },
  { id: 'Cinzel', name: 'Cinzel (Institucional Solemne)', category: 'Serif' },
  { id: 'PT Serif', name: 'PT Serif (Contemporánea & Nítida)', category: 'Serif' },
  { id: 'Georgia', name: 'Georgia (Sistema Estándar)', category: 'Serif' },
];

export const AVAILABLE_BODY_FONTS = [
  { id: 'Inter', name: 'Inter (Moderna Hiper-legible)', category: 'Sans-Serif' },
  { id: 'Plus Jakarta Sans', name: 'Plus Jakarta Sans (Editorial UI)', category: 'Sans-Serif' },
  { id: 'Roboto', name: 'Roboto (Google Editorial)', category: 'Sans-Serif' },
  { id: 'Montserrat', name: 'Montserrat (Geométrica Distintiva)', category: 'Sans-Serif' },
  { id: 'Open Sans', name: 'Open Sans (Cálida y Neutral)', category: 'Sans-Serif' },
];

export const WHITE_LABEL_PRESETS: WhiteLabelPreset[] = [
  {
    id: 'contacto_default',
    name: 'Contacto · Clásico',
    description: 'Borgoña, tinta oscura y tonos de papel cálido para una portada regional tradicional.',
    config: {
      colors: {
        primary: '#881337',
        primaryHover: '#4c0519',
        accent: '#a33a35',
        topBarBg: '#f4f0ea',
        topBarText: '#57534e',
        navBg: '#eee9e2',
        navText: '#1c1917',
        pageBg: '#f4f1eb',
        mastheadBg: '#ffffff',
        mastheadText: '#0c0a09',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Merriweather',
        bodyFont: 'Open Sans',
        headingWeight: '900',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'classic_double_rule',
      },
    },
  },
  {
    id: 'classic_navy',
    name: 'Edición · Marina',
    description: 'Azul tinta con papel frío y acento cobrizo discreto; formal, sin superficies oscuras apiladas.',
    config: {
      colors: {
        primary: '#1e3a8a',
        primaryHover: '#172554',
        accent: '#9b542f',
        topBarBg: '#e9edf0',
        topBarText: '#3d4c59',
        navBg: '#e2e8ec',
        navText: '#263746',
        pageBg: '#eef1f2',
        mastheadBg: '#fbfcfc',
        mastheadText: '#0f172a',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Playfair Display',
        bodyFont: 'Open Sans',
        headingWeight: '800',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'modern_centered',
      },
    },
  },
  {
    id: 'modern_crimson',
    name: 'Edición · Contemporánea',
    description: 'Carbón, blanco roto y rojo teja con una navegación ligera para lectura digital.',
    config: {
      colors: {
        primary: '#303b42',
        primaryHover: '#1d292f',
        accent: '#b4493d',
        topBarBg: '#f0f0ed',
        topBarText: '#4c5355',
        navBg: '#e6e7e4',
        navText: '#303b42',
        pageBg: '#f1f1ee',
        mastheadBg: '#fbfbf9',
        mastheadText: '#252c30',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'Lora',
        bodyFont: 'Open Sans',
        headingWeight: '700',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: false,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'clean_compact',
      },
    },
  },
  {
    id: 'forest_emerald',
    name: 'Edición · Llanos',
    description: 'Verde de monte, papel salvia y un matiz tierra inspirado en el paisaje regional.',
    config: {
      colors: {
        primary: '#315847',
        primaryHover: '#244435',
        accent: '#975b36',
        topBarBg: '#e9eee7',
        topBarText: '#405448',
        navBg: '#e1e9df',
        navText: '#315044',
        pageBg: '#eef1e9',
        mastheadBg: '#fafbf7',
        mastheadText: '#263d32',
        cardBg: '#ffffff',
      },
      typography: {
        headingFont: 'PT Serif',
        bodyFont: 'Open Sans',
        headingWeight: '700',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'classic_double_rule',
      },
    },
  },
  {
    id: 'warm_amber',
    name: 'Edición · Papel',
    description: 'Tonos hueso, tinta nogal y acento ocre envejecido, como una edición impresa bien conservada.',
    config: {
      colors: {
        primary: '#68452b',
        primaryHover: '#4e3320',
        accent: '#935b1f',
        topBarBg: '#efe7d9',
        topBarText: '#5f4937',
        navBg: '#e7ddcb',
        navText: '#57422e',
        pageBg: '#f1eadf',
        mastheadBg: '#faf6ee',
        mastheadText: '#3b2c21',
        cardBg: '#fffdf8',
      },
      typography: {
        headingFont: 'Merriweather',
        bodyFont: 'Open Sans',
        headingWeight: '700',
        scale: 'normal',
      },
      features: {
        showBreakingNewsTicker: true,
        showWeatherWidget: true,
        showCitizenSubmissionButton: true,
        showSocialShareButtons: true,
        mastheadLayout: 'classic_double_rule',
      },
    },
  },
];
